# Generated by Django 4.2.7 on 2023-11-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='is_completed',
        ),
    ]
