# Generated by Django 4.2.7 on 2023-11-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todotask_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
