# Generated by Django 4.2.7 on 2023-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_taskreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='owner_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
